// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {services} from '../models';

export function CreateFile(arg1:string,arg2:string):Promise<void>;

export function CreateFolder(arg1:string,arg2:string):Promise<void>;

export function Delete(arg1:string):Promise<void>;

export function FileExists(arg1:string):Promise<boolean>;

export function GetConfig():Promise<Record<string, string>>;

export function GetFileTree():Promise<Array<services.FileNode>>;

export function MoveFile(arg1:string,arg2:string):Promise<void>;

export function ReadFile(arg1:string):Promise<string>;

export function Rename(arg1:string,arg2:string):Promise<void>;

export function SetTheme(arg1:string):Promise<void>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
