import { EditorView } from "codemirror";
import { HighlightStyle, syntaxHighlighting } from "@codemirror/language";
import { tags } from "@lezer/highlight";

const darkColors = {
    background: '#0f1419',
    foreground: '#e5e7eb',
    selection: 'rgba(5, 150, 105, 0.3)',
    cursor: '#059669',
    activeLine: 'rgba(5, 150, 105, 0.1)',
    activeLineGutter: '#243044',
    guttersBackground: '#1a2332',
    guttersBorder: '#374357',
    gutterForeground: '#6b7280',
    lineNumberForeground: '#6b7280',
    matchingBracket: 'rgba(5, 150, 105, 0.4)',
};

const lightColors = {
    background: '#ffffff',
    foreground: '#1f2937',
    selection: 'rgba(5, 150, 105, 0.2)',
    cursor: '#059669',
    activeLine: 'rgba(5, 150, 105, 0.05)',
    activeLineGutter: '#e8f0ec',
    guttersBackground: '#f3f7f5',
    guttersBorder: '#d1d9e0',
    gutterForeground: '#9ca3af',
    lineNumberForeground: '#9ca3af',
    matchingBracket: 'rgba(5, 150, 105, 0.3)',
};

const darkSyntaxColors = {
    comment: '#6b7280',
    heading: '#10b981',
    emphasis: '#e5e7eb',
    strong: '#ffffff',
    link: '#059669',
    url: '#7dd3fc',
    meta: '#7dd3fc',
    keyword: '#f472b6',
    atom: '#f472b6',
    number: '#fb923c',
    string: '#4ade80',
    variableName: '#e5e7eb',
    definition: '#7dd3fc',
    propertyName: '#7dd3fc',
    operator: '#94a3b8',
    punctuation: '#94a3b8',
    bracket: '#94a3b8',
    tagName: '#f472b6',
    attributeName: '#7dd3fc',
    attributeValue: '#4ade80',
    invalid: '#f87171',
    content: '#e5e7eb',
};

const lightSyntaxColors = {
    comment: '#9ca3af',
    heading: '#059669',
    emphasis: '#1f2937',
    strong: '#1f2937',
    link: '#047857',
    url: '#0369a1',
    meta: '#0369a1',
    keyword: '#db2777',
    atom: '#db2777',
    number: '#ea580c',
    string: '#16a34a',
    variableName: '#1f2937',
    definition: '#0369a1',
    propertyName: '#0369a1',
    operator: '#6b7280',
    punctuation: '#6b7280',
    bracket: '#6b7280',
    tagName: '#db2777',
    attributeName: '#0369a1',
    attributeValue: '#16a34a',
    invalid: '#dc2626',
    content: '#1f2937',
};

const darkHighlightStyle = HighlightStyle.define([
    { tag: tags.comment, color: darkSyntaxColors.comment, fontStyle: 'italic' },
    { tag: tags.heading, color: darkSyntaxColors.heading, fontWeight: 'bold' },
    { tag: tags.heading1, color: darkSyntaxColors.heading, fontWeight: 'bold' },
    { tag: tags.heading2, color: darkSyntaxColors.heading, fontWeight: 'bold' },
    { tag: tags.heading3, color: darkSyntaxColors.heading, fontWeight: 'bold' },
    { tag: tags.heading4, color: darkSyntaxColors.heading, fontWeight: 'bold' },
    { tag: tags.heading5, color: darkSyntaxColors.heading, fontWeight: 'bold' },
    { tag: tags.heading6, color: darkSyntaxColors.heading, fontWeight: 'bold' },
    { tag: tags.emphasis, color: darkSyntaxColors.emphasis, fontStyle: 'italic' },
    { tag: tags.strong, color: darkSyntaxColors.strong, fontWeight: 'bold' },
    { tag: tags.link, color: darkSyntaxColors.link, textDecoration: 'underline' },
    { tag: tags.url, color: darkSyntaxColors.url },
    { tag: tags.meta, color: darkSyntaxColors.meta },
    { tag: tags.keyword, color: darkSyntaxColors.keyword },
    { tag: tags.atom, color: darkSyntaxColors.atom },
    { tag: tags.bool, color: darkSyntaxColors.atom },
    { tag: tags.null, color: darkSyntaxColors.atom },
    { tag: tags.number, color: darkSyntaxColors.number },
    { tag: tags.integer, color: darkSyntaxColors.number },
    { tag: tags.float, color: darkSyntaxColors.number },
    { tag: tags.string, color: darkSyntaxColors.string },
    { tag: tags.literal, color: darkSyntaxColors.string },
    { tag: tags.inserted, color: darkSyntaxColors.string },
    { tag: tags.variableName, color: darkSyntaxColors.variableName },
    { tag: tags.definition(tags.variableName), color: darkSyntaxColors.definition },
    { tag: tags.local(tags.variableName), color: darkSyntaxColors.variableName },
    { tag: tags.propertyName, color: darkSyntaxColors.propertyName },
    { tag: tags.definition(tags.propertyName), color: darkSyntaxColors.definition },
    { tag: tags.operator, color: darkSyntaxColors.operator },
    { tag: tags.arithmeticOperator, color: darkSyntaxColors.operator },
    { tag: tags.logicOperator, color: darkSyntaxColors.operator },
    { tag: tags.bitwiseOperator, color: darkSyntaxColors.operator },
    { tag: tags.compareOperator, color: darkSyntaxColors.operator },
    { tag: tags.punctuation, color: darkSyntaxColors.punctuation },
    { tag: tags.separator, color: darkSyntaxColors.punctuation },
    { tag: tags.bracket, color: darkSyntaxColors.bracket },
    { tag: tags.angleBracket, color: darkSyntaxColors.bracket },
    { tag: tags.squareBracket, color: darkSyntaxColors.bracket },
    { tag: tags.paren, color: darkSyntaxColors.bracket },
    { tag: tags.brace, color: darkSyntaxColors.bracket },
    { tag: tags.content, color: darkSyntaxColors.content },
    { tag: tags.monospace, color: darkSyntaxColors.string },
    { tag: tags.tagName, color: darkSyntaxColors.tagName },
    { tag: tags.attributeName, color: darkSyntaxColors.attributeName },
    { tag: tags.attributeValue, color: darkSyntaxColors.attributeValue },
    { tag: tags.invalid, color: darkSyntaxColors.invalid, textDecoration: 'line-through' },
    { tag: tags.processingInstruction, color: darkSyntaxColors.meta },
    { tag: tags.contentSeparator, color: darkSyntaxColors.punctuation },
    { tag: tags.list, color: darkSyntaxColors.keyword },
    { tag: tags.quote, color: darkSyntaxColors.emphasis },
]);

const lightHighlightStyle = HighlightStyle.define([
    { tag: tags.comment, color: lightSyntaxColors.comment, fontStyle: 'italic' },
    { tag: tags.heading, color: lightSyntaxColors.heading, fontWeight: 'bold' },
    { tag: tags.heading1, color: lightSyntaxColors.heading, fontWeight: 'bold' },
    { tag: tags.heading2, color: lightSyntaxColors.heading, fontWeight: 'bold' },
    { tag: tags.heading3, color: lightSyntaxColors.heading, fontWeight: 'bold' },
    { tag: tags.heading4, color: lightSyntaxColors.heading, fontWeight: 'bold' },
    { tag: tags.heading5, color: lightSyntaxColors.heading, fontWeight: 'bold' },
    { tag: tags.heading6, color: lightSyntaxColors.heading, fontWeight: 'bold' },
    { tag: tags.emphasis, color: lightSyntaxColors.emphasis, fontStyle: 'italic' },
    { tag: tags.strong, color: lightSyntaxColors.strong, fontWeight: 'bold' },
    { tag: tags.link, color: lightSyntaxColors.link, textDecoration: 'underline' },
    { tag: tags.url, color: lightSyntaxColors.url },
    { tag: tags.meta, color: lightSyntaxColors.meta },
    { tag: tags.keyword, color: lightSyntaxColors.keyword },
    { tag: tags.atom, color: lightSyntaxColors.atom },
    { tag: tags.bool, color: lightSyntaxColors.atom },
    { tag: tags.null, color: lightSyntaxColors.atom },
    { tag: tags.number, color: lightSyntaxColors.number },
    { tag: tags.integer, color: lightSyntaxColors.number },
    { tag: tags.float, color: lightSyntaxColors.number },
    { tag: tags.string, color: lightSyntaxColors.string },
    { tag: tags.literal, color: lightSyntaxColors.string },
    { tag: tags.inserted, color: lightSyntaxColors.string },
    { tag: tags.variableName, color: lightSyntaxColors.variableName },
    { tag: tags.definition(tags.variableName), color: lightSyntaxColors.definition },
    { tag: tags.local(tags.variableName), color: lightSyntaxColors.variableName },
    { tag: tags.propertyName, color: lightSyntaxColors.propertyName },
    { tag: tags.definition(tags.propertyName), color: lightSyntaxColors.definition },
    { tag: tags.operator, color: lightSyntaxColors.operator },
    { tag: tags.arithmeticOperator, color: lightSyntaxColors.operator },
    { tag: tags.logicOperator, color: lightSyntaxColors.operator },
    { tag: tags.bitwiseOperator, color: lightSyntaxColors.operator },
    { tag: tags.compareOperator, color: lightSyntaxColors.operator },
    { tag: tags.punctuation, color: lightSyntaxColors.punctuation },
    { tag: tags.separator, color: lightSyntaxColors.punctuation },
    { tag: tags.bracket, color: lightSyntaxColors.bracket },
    { tag: tags.angleBracket, color: lightSyntaxColors.bracket },
    { tag: tags.squareBracket, color: lightSyntaxColors.bracket },
    { tag: tags.paren, color: lightSyntaxColors.bracket },
    { tag: tags.brace, color: lightSyntaxColors.bracket },
    { tag: tags.content, color: lightSyntaxColors.content },
    { tag: tags.monospace, color: lightSyntaxColors.string },
    { tag: tags.tagName, color: lightSyntaxColors.tagName },
    { tag: tags.attributeName, color: lightSyntaxColors.attributeName },
    { tag: tags.attributeValue, color: lightSyntaxColors.attributeValue },
    { tag: tags.invalid, color: lightSyntaxColors.invalid, textDecoration: 'line-through' },
    { tag: tags.processingInstruction, color: lightSyntaxColors.meta },
    { tag: tags.contentSeparator, color: lightSyntaxColors.punctuation },
    { tag: tags.list, color: lightSyntaxColors.keyword },
    { tag: tags.quote, color: lightSyntaxColors.emphasis },
]);

export const carmemDark = EditorView.theme({
    '&': {
        backgroundColor: darkColors.background,
        color: darkColors.foreground,
        height: '100%',
    },
    '.cm-content': {
        caretColor: darkColors.cursor,
        padding: '0.5rem 0',
    },
    '.cm-cursor, .cm-dropCursor': {
        borderLeftColor: darkColors.cursor,
        borderLeftWidth: '2px',
    },
    '&.cm-focused .cm-selectionBackground, .cm-selectionBackground, .cm-content ::selection': {
        backgroundColor: darkColors.selection,
    },
    '.cm-activeLine': {
        backgroundColor: darkColors.activeLine,
    },
    '.cm-gutters': {
        backgroundColor: darkColors.guttersBackground,
        color: darkColors.gutterForeground,
        border: 'none',
        borderRight: `1px solid ${darkColors.guttersBorder}`,
    },
    '.cm-activeLineGutter': {
        backgroundColor: darkColors.activeLineGutter,
        color: darkColors.foreground,
    },
    '.cm-lineNumbers .cm-gutterElement': {
        color: darkColors.lineNumberForeground,
        padding: '0 0.75rem 0 0.5rem',
        minWidth: '3rem',
    },
    '.cm-foldPlaceholder': {
        backgroundColor: 'transparent',
        border: 'none',
        color: darkColors.cursor,
    },
    '.cm-tooltip': {
        backgroundColor: darkColors.guttersBackground,
        border: `1px solid ${darkColors.guttersBorder}`,
        borderRadius: '4px',
    },
    '.cm-tooltip-autocomplete': {
        '& > ul > li[aria-selected]': {
            backgroundColor: darkColors.selection,
        }
    },
    '.cm-matchingBracket': {
        backgroundColor: darkColors.matchingBracket,
        color: 'white !important',
        borderRadius: '2px',
    },
    '.cm-searchMatch': {
        backgroundColor: 'rgba(251, 191, 36, 0.3)',
        outline: '1px solid rgba(251, 191, 36, 0.5)',
    },
    '.cm-searchMatch.cm-searchMatch-selected': {
        backgroundColor: 'rgba(5, 150, 105, 0.3)',
    },
}, { dark: true });

export const carmemLight = EditorView.theme({
    '&': {
        backgroundColor: lightColors.background,
        color: lightColors.foreground,
        height: '100%',
    },
    '.cm-content': {
        caretColor: lightColors.cursor,
        padding: '0.5rem 0',
    },
    '.cm-cursor, .cm-dropCursor': {
        borderLeftColor: lightColors.cursor,
        borderLeftWidth: '2px',
    },
    '&.cm-focused .cm-selectionBackground, .cm-selectionBackground, .cm-content ::selection': {
        backgroundColor: lightColors.selection,
    },
    '.cm-activeLine': {
        backgroundColor: lightColors.activeLine,
    },
    '.cm-gutters': {
        backgroundColor: lightColors.guttersBackground,
        color: lightColors.gutterForeground,
        border: 'none',
        borderRight: `1px solid ${lightColors.guttersBorder}`,
    },
    '.cm-activeLineGutter': {
        backgroundColor: lightColors.activeLineGutter,
        color: lightColors.foreground,
    },
    '.cm-lineNumbers .cm-gutterElement': {
        color: lightColors.lineNumberForeground,
        padding: '0 0.75rem 0 0.5rem',
        minWidth: '3rem',
    },
    '.cm-foldPlaceholder': {
        backgroundColor: 'transparent',
        border: 'none',
        color: lightColors.cursor,
    },
    '.cm-tooltip': {
        backgroundColor: lightColors.guttersBackground,
        border: `1px solid ${lightColors.guttersBorder}`,
        borderRadius: '4px',
    },
    '.cm-tooltip-autocomplete': {
        '& > ul > li[aria-selected]': {
            backgroundColor: lightColors.selection,
        }
    },
    '.cm-matchingBracket': {
        backgroundColor: lightColors.matchingBracket,
        color: '#047857 !important',
        borderRadius: '2px',
    },
    '.cm-searchMatch': {
        backgroundColor: 'rgba(251, 191, 36, 0.3)',
        outline: '1px solid rgba(251, 191, 36, 0.5)',
    },
    '.cm-searchMatch.cm-searchMatch-selected': {
        backgroundColor: 'rgba(5, 150, 105, 0.3)',
    },
}, { dark: false });

export const carmemDarkSyntax = syntaxHighlighting(darkHighlightStyle);
export const carmemLightSyntax = syntaxHighlighting(lightHighlightStyle);
