name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - platform: 'windows/amd64'
            os: 'windows-latest'

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Wails App
        uses: host-uk/build@v4
        with:
          build-name: carmem
          build-platform: ${{ matrix.platform }}
          nsis: ${{ matrix.platform == 'windows/amd64' && 'true' || 'false' }}
          package: 'true'
          wails-version: 'v2.11.0'
