name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - uses: snider/build@v3
        with:
          build-name: carmem
          build-platform: linux/amd64
          package: true
